# Generated by Django 3.2 on 2021-04-11 23:19

from django.db import migrations, models
import imager.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0002_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='file',
            field=models.FileField(default=1, upload_to=imager.models.scramble_uploaded_filename, verbose_name='Upload field'),
            preserve_default=False,
        ),
    ]
