# Generated by Django 3.2 on 2021-04-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0003_uploadimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='file',
        ),
    ]
