# Generated by Django 3.2 on 2021-04-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='file',
        ),
    ]
