# Generated by Django 3.2 on 2021-04-12 13:03

from django.db import migrations, models
import imager.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0007_rename_image_photo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(default='pots/default.jpg', upload_to=imager.models.scramble_uploaded_filename),
        ),
    ]
