# Generated by Django 3.2 on 2021-04-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0008_auto_20210412_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='file',
            new_name='image',
        ),
    ]
