# Generated by Django 3.2 on 2021-04-12 14:18

from django.db import migrations, models
import imager.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0009_rename_file_uploadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(default='pots/default.jpg', upload_to=imager.models.user_directory_path),
        ),
    ]
